version: "3.9"
services:
  db:
    image: "mysql:8.0.26"
    ports:
      - "3306:3306"
    volumes:
      - "${MYSQL_INIT_SCRIPT_PATH:-./mysql-init.sql}:/docker-entrypoint-initdb.d/mysql-init.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    healthcheck:
      test: mysqladmin ping -h localhost -u root -proot
      timeout: 3s
      retries: 3
